/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/opportunities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Opportunities
         * @description List currently-open opportunities, filtered and sorted server-side.
         *
         *     Expired opportunities (deadline in the past) are always excluded --
         *     this is enforced here, not left to the frontend, so it holds regardless
         *     of which client calls this endpoint or how stale its own state is.
         */
        get: operations["list_opportunities_api_opportunities__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Filters
         * @description Distinct filter values (and counts) across the currently-open
         *     dataset only -- so the filter UI never offers a country/type/sector
         *     that has nothing but expired opportunities behind it.
         */
        get: operations["get_filters_api_opportunities_filters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities/{opportunity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Opportunity */
        get: operations["get_opportunity_api_opportunities__opportunity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Opportunities
         * @description Trigger an immediate scrape of all sources instead of waiting for the
         *     next scheduled run. Runs in the background; check /api/opportunities
         *     shortly after to see results.
         */
        post: operations["refresh_opportunities_api_opportunities_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscribers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Subscribers */
        get: operations["list_subscribers_api_subscribers__get"];
        put?: never;
        /** Add Subscriber */
        post: operations["add_subscriber_api_subscribers__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscribers/test-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Test Email
         * @description Sends a one-off sample digest to every current subscriber, using the
         *     exact same send_digest() path the real scraper uses -- lets you verify
         *     email delivery works without waiting for a genuinely new opportunity to
         *     be scraped.
         */
        post: operations["send_test_email_api_subscribers_test_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscribers/unsubscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unsubscribe
         * @description One-click unsubscribe link used in the digest email's footer -- plain
         *     GET so it works from a link click in any email client, no login/JS
         *     needed. Always returns a friendly confirmation page (idempotent) rather
         *     than erroring if the email was already removed.
         */
        get: operations["unsubscribe_api_subscribers_unsubscribe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscribers/{subscriber_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Subscriber */
        delete: operations["remove_subscriber_api_subscribers__subscriber_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_admin_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List All Opportunities
         * @description Admin listing -- deliberately NOT restricted to open/unexpired
         *     opportunities like the public endpoint, since admins need to find and
         *     correct expired or incorrectly-parsed records too.
         */
        get: operations["list_all_opportunities_api_admin_opportunities_get"];
        put?: never;
        /** Create Opportunity */
        post: operations["create_opportunity_api_admin_opportunities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/opportunities/{opportunity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Opportunity */
        put: operations["update_opportunity_api_admin_opportunities__opportunity_id__put"];
        post?: never;
        /** Delete Opportunity */
        delete: operations["delete_opportunity_api_admin_opportunities__opportunity_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DocumentItem */
        DocumentItem: {
            /** Label */
            label: string;
            /** Url */
            url: string;
        };
        /** DocumentOut */
        DocumentOut: {
            /** Label */
            label: string;
            /** Url */
            url: string;
        };
        /** ExtraFieldOut */
        ExtraFieldOut: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** ExtraItem */
        ExtraItem: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
        };
        /** OpportunityIntake */
        OpportunityIntake: {
            /** Source */
            source: string;
            /** Title */
            title: string;
            /** Link */
            link: string;
            /** Organization */
            organization?: string;
            /** Country */
            country?: string;
            /** Opportunity Type */
            opportunity_type?: string;
            /** Sector */
            sector?: string;
            /** Description */
            description?: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at?: string;
            /**
             * Deadline
             * Format: date-time
             */
            deadline?: string;
            /** Reference */
            reference?: string;
            /** Eligibility */
            eligibility?: string;
            /** Contact Info */
            contact_info?: string;
            /**
             * Documents
             * @default []
             */
            documents: components["schemas"]["DocumentItem"][];
            /**
             * Extra
             * @default []
             */
            extra: components["schemas"]["ExtraItem"][];
        };
        /**
         * OpportunityOut
         * @description Mirrors Opportunity.to_dict() field-for-field. This is the response
         *     shape for every public opportunity endpoint -- declaring it here (instead
         *     of the previous bare `response_model=dict`) is what makes the OpenAPI
         *     schema actually describe the payload, which is what any client (mobile
         *     included) needs to generate real types from it rather than `Record<string,
         *     any>`. Purely additive: the JSON on the wire is unchanged, since to_dict()
         *     already produces exactly these types.
         */
        OpportunityOut: {
            /** Id */
            id: number;
            /** Source */
            source: string;
            /** Title */
            title: string;
            /** Link */
            link: string;
            /** Excerpt */
            excerpt?: string;
            /** Description */
            description?: string;
            /** Published At */
            published_at?: string;
            /** Deadline */
            deadline?: string;
            /**
             * Matched Keywords
             * @default []
             */
            matched_keywords: string[];
            /** Organization */
            organization?: string;
            /** Country */
            country?: string;
            /** Reference */
            reference?: string;
            /** Opportunity Type */
            opportunity_type?: string;
            /** Sector */
            sector?: string;
            /** Eligibility */
            eligibility?: string;
            /** Contact Info */
            contact_info?: string;
            /**
             * Documents
             * @default []
             */
            documents: components["schemas"]["DocumentOut"][];
            /**
             * Extra
             * @default []
             */
            extra: components["schemas"]["ExtraFieldOut"][];
            /**
             * Ingestion Method
             * @default automated
             */
            ingestion_method: string;
            /** Fit Status */
            fit_status?: string;
            /** Fit Score */
            fit_score?: number;
            /** Fit Tier */
            fit_tier?: string;
            /** Fit Analysis */
            fit_analysis?: Record<string, never>;
            /** Created At */
            created_at?: string;
        };
        /** SubscriberCreate */
        SubscriberCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_opportunities_api_opportunities__get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                source?: string;
                search?: string;
                country?: string;
                opportunity_type?: string;
                sector?: string;
                deadline_within_days?: number;
                published_within_days?: number;
                deadline_from?: string;
                deadline_to?: string;
                published_from?: string;
                published_to?: string;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_filters_api_opportunities_filters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_opportunity_api_opportunities__opportunity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_opportunities_api_opportunities_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_subscribers_api_subscribers__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_subscriber_api_subscribers__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriberCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_test_email_api_subscribers_test_email_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unsubscribe_api_subscribers_unsubscribe_get: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_subscriber_api_subscribers__subscriber_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                subscriber_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_admin_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_opportunities_api_admin_opportunities_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                search?: string;
                source?: string;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_opportunity_api_admin_opportunities_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpportunityIntake"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_opportunity_api_admin_opportunities__opportunity_id__put: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: {
                authorization?: string;
            };
            path: {
                opportunity_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpportunityIntake"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_opportunity_api_admin_opportunities__opportunity_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                opportunity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
